[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100
force_alphabetical_sort_within_sections = true
force_sort_within_sections = true


[tool.briefcase]
project_name = "WinSnap"
bundle = "ult.example"
version = "1.0.0"
url = ""
license = "MIT"
author = 'Perry Vargas'
author_email = "perrybvargas@gmail.com"

[tool.briefcase.app.winsnap]
formal_name = "WinSnap"
description = "Snap windows into a customizable grid"
icon = "winsnap/resources/icon"
sources = ['winsnap']
requires = [
    "psutil==5.8.0",
    "pywin32==288",
    "pywinauto==0.6.8",
    "dearpygui==0.6.42",
]


[tool.briefcase.app.winsnap.macOS]
requires = []

[tool.briefcase.app.winsnap.linux]
requires = []

[tool.briefcase.app.winsnap.windows]
requires = []

# Mobile deployments
[tool.briefcase.app.winsnap.iOS]
requires = []

[tool.briefcase.app.winsnap.android]
requires = []
